"""Found one to many bug

Revision ID: e68b789d88bd
Revises: 1028351d1afb
Create Date: 2026-03-14 09:46:07.804468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68b789d88bd'
down_revision = '1028351d1afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_session_id_sessions'), type_='foreignkey')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sessions_event_id_events'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sessions_event_id_events'), type_='foreignkey')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_events_session_id_sessions'), 'sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
